---
title: "Habitat Suitability Report"
output: 
  - github_document:
      toc: true
      html_preview: false
  - html_document:
      toc: true
params: 
  cfg_file: NULL 
---

```{r pre_setup, echo=FALSE, message=FALSE}
source("/mnt/ecocast/projects/koliveira/subprojects/carcharodon/setup.R")
cfg = charlier::read_config(params$cfg_file)
vpars = charlier::parse_version(cfg$version)
if (FALSE) {
  cfg = charlier::read_config("/mnt/ecocast/projects/koliveira/subprojects/carcharodon/workflows/tidy_md/m21.10076.yaml")
}

```

```{r setup, echo=FALSE, message=FALSE}
#knitr::opts_knit$set(root.dir = dirname(cfg$root_path))
parsed_wf_v = charlier::parse_version(cfg$t_wf_version)
parsed_fore_v = charlier::parse_version(cfg$t_rep_fore_version)
parsed_now_v = charlier::parse_version(cfg$t_rep_now_version)
```

## Inputs
```{r report_inputs, echo=FALSE, results='asis'}
cat(paste0(
  "- Species: ", cfg$message$species, "\n",
  "- Thinning: ", cfg$message$thin_message, "\n",
  "- Ratio: ", cfg$message$obs_bg_ratio, "\n",
  "- Spatial extent: ", cfg$message$spat_extent, "\n",
  "- Covariates used: ", cfg$message$covs, "\n",
  "- Metrics: ", cfg$message$metrics, "\n"
))
```

## Nowcast and Forecast Maps

Random Forest Nowcast and Forecast

```{r rfplots, fig.show="hold", out.width="45%", echo=FALSE}
rf_now = fig_path(root = cfg$root_path,
                  version = cfg$t_rep_now_version,
                  model_type = "rf")
rf_fore = fig_path(root = cfg$root_path,
                   version = cfg$t_rep_fore_version,
                   model_type = "rf")
```

```{r embed_rf_figures, echo=FALSE, results='asis'}
embed_fig(list(rf_now, rf_fore), labels = c("Nowcast", "Forecast: RCP 8.5 2075"), width = "45%")
```

Boosted Trees Nowcast and Forecast

```{r btplots, fig.show="hold", out.width="45%", echo=FALSE}
bt_now = fig_path(root = cfg$root_path, 
                  version = cfg$t_rep_now_version, 
                  model_type = "bt")
bt_fore = fig_path(root = cfg$root_path,
                   version = cfg$t_rep_fore_version,
                   model_type = "bt")
```

```{r embed_bt_figures, echo=FALSE, results='asis'}
embed_fig(list(bt_now, bt_fore), labels = c("Nowcast", "Forecast: RCP 8.5 2075"), width = "45%")
```


Maxnet Trees Nowcast and Forecast

```{r maxentplots, fig.show="hold", out.width="45%", echo=FALSE}
maxent_now = fig_path(root = cfg$root_path, 
                  version = cfg$t_rep_now_version, 
                  model_type = "maxent")
maxent_fore = fig_path(root = cfg$root_path,
                   version = cfg$t_rep_fore_version,
                   model_type = "maxent")
```

```{r embed_maxent_figures, echo=FALSE, results='asis'}
embed_fig(list(maxent_now, maxent_fore), labels = c("Nowcast", "Forecast: RCP 8.5 2075"), width = "45%")
```

GAM Nowcast and Forecast

```{r gamplots, fig.show="hold", out.width="45%", echo=FALSE}
gam_now = fig_path(root = cfg$root_path, 
                  version = cfg$t_rep_now_version, 
                  model_type = "gam")
gam_fore = fig_path(root = cfg$root_path,
                   version = cfg$t_rep_fore_version,
                   model_type = "gam")
```

```{r embed_gam_figures, echo=FALSE, results='asis'}
embed_fig(list(gam_now, gam_fore), labels = c("Nowcast", "Forecast: RCP 8.5 2075"), width = "45%")
```

GLM Nowcast and Forecast

```{r glmplots, fig.show="hold", out.width="45%", echo=FALSE}
glm_now = fig_path(root = cfg$root_path, 
                  version = cfg$t_rep_now_version, 
                  model_type = "glm")
glm_fore = fig_path(root = cfg$root_path,
                   version = cfg$t_rep_fore_version,
                   model_type = "glm")
```

```{r embed_glm_figures, echo=FALSE, results='asis'}
embed_fig(list(glm_now, glm_fore), labels = c("Nowcast", "Forecast: RCP 8.5 2075"), width = "45%")
```

## Metrics

```{r metrics, echo=FALSE, message=FALSE}
rf_metrics = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_rf_final_metrics.csv")), show_col_types = FALSE) |> 
  dplyr::select(c(".metric", ".estimate")) |>
  tidyr::pivot_wider(names_from = .metric,
                     values_from = .estimate)

bt_metrics = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_bt_final_metrics.csv")), show_col_types = FALSE) |> 
  dplyr::select(c(".metric", ".estimate")) |>
  tidyr::pivot_wider(names_from = .metric,
                     values_from = .estimate)

maxnet_metrics = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_maxent_final_metrics.csv")), show_col_types = FALSE) |> 
  dplyr::select(c(".metric", ".estimate")) |>
  tidyr::pivot_wider(names_from = .metric,
                     values_from = .estimate)

gam_metrics = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_gam_final_metrics.csv")), show_col_types = FALSE) |> 
  dplyr::select(c(".metric", ".estimate")) |>
  tidyr::pivot_wider(names_from = .metric,
                     values_from = .estimate)

glm_metrics = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_glm_final_metrics.csv")), show_col_types = FALSE) |> 
  dplyr::select(c(".metric", ".estimate")) |>
  tidyr::pivot_wider(names_from = .metric,
                     values_from = .estimate)

all_metrics = dplyr::bind_rows(list(rf = rf_metrics, bt = bt_metrics, maxnet = maxnet_metrics, gam = gam_metrics, glm = glm_metrics),
                               .id = "model_type")
knitr::kable(all_metrics, caption = "Metrics by model type")
```

## Variable Importance

```{r variable_importance, echo=FALSE, message=FALSE}
withr::with_dir("/mnt/ecocast/projects/koliveira/subprojects/carcharodon", {
rf_vi = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_rf_vi.csv")), show_col_types = FALSE) |>
  dplyr::select(c("var", "importance")) 

bt_vi = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_bt_vi.csv")), show_col_types = FALSE) |>
  dplyr::select(c("var", "importance")) 

maxnet_vi = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_maxent_vi.csv")), show_col_types = FALSE) |>
  dplyr::select(c("var", "importance")) 

gam_vi = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_gam_vi.csv")), show_col_types = FALSE) |>
  dplyr::select(c("var", "importance")) 

glm_vi = readr::read_csv(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_glm_vi.csv")), show_col_types = FALSE) |>
  dplyr::select(c("var", "importance")) 

all_vi = dplyr::bind_rows(list(rf = rf_vi, bt = bt_vi, maxent = maxnet_vi, gam = gam_vi, glm = glm_vi), .id = "model_type")

vi_plot = ggplot() +
    geom_bar(data = all_vi, aes(x = model_type, y = importance, fill = var),
             position = "fill", stat = "identity") +
    theme_classic() +
  scale_fill_viridis_d() +
    ggtitle(cfg$graphics$vi_title) +
    labs(x = cfg$graphics$x, 
         y = cfg$graphics$vi_y)

vi_fig_path = file.path(cfg$root_path,
                          "tidy_md/versions",
                          vpars["major"],
                          vpars["minor"],
                          paste0(cfg$version, "_tidy_compiled_files"),
                          "figure-gfm",
                          "variable_importance-1.png")

  ggplot2::ggsave(vi_fig_path, plot = vi_plot, width = 8, height = 6, dpi = 300)
})
```

```{r embed_vi, echo=FALSE, results='asis'}
vi_paths = vi_path(root = cfg$root_path, version = cfg$version)

embed_vi(path_obj = vi_paths)
```

## Partial Dependence
```{r partial_dependence, echo=FALSE, message=FALSE}
withr::with_dir("/mnt/ecocast/projects/koliveira/subprojects/carcharodon", {
rf_pd = readr::read_rds(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_rf_pd.rds")))

bt_pd = readr::read_rds(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_bt_pd.rds")))

maxnet_pd = readr::read_rds(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_maxent_pd.rds")))

gam_pd = readr::read_rds(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_gam_pd.rds")))

glm_pd = readr::read_rds(file.path(cfg$root_path, "tidy_workflow/versions", parsed_wf_v["major"], parsed_wf_v["minor"], cfg$t_wf_version, paste0(cfg$t_wf_version, "_glm_pd.rds")))

all_pd = list(rf = rf_pd, bt = bt_pd, maxent = maxnet_pd, gam = gam_pd, glm = glm_pd)
tidy_pd = purrr::imap_dfr(all_pd, function(model_list, model_name) {
  imap_dfr(model_list, function(df, variable_name) {
    df |>
      mutate(model = model_name,
             variable = variable_name)
  })
}) |>
  mutate(pd = dplyr::if_else(.data$model %in% c("gam", "glm"), 1-pd, pd))

pd_plot = ggplot() +
  geom_line(data = tidy_pd, aes(x = bin_mean, y = pd, color = model), linewidth = 1) +
  facet_wrap(~ variable, scales = "free_x", labeller = as_labeller(covar_relabel)) +
  labs(y = "Partial dependence") +
  scale_color_viridis_d(name = "Model",
                        labels = model_relabel) +
  theme_classic()

pd_fig_path = file.path(cfg$root_path,
                          "tidy_md/versions",
                          vpars["major"],
                          vpars["minor"],
                          paste0(cfg$version, "_tidy_compiled_files"),
                          "figure-gfm",
                          "partial_dependence-1.png")

  ggplot2::ggsave(pd_fig_path, plot = pd_plot, width = 8, height = 6, dpi = 300)
})
```

```{r embed_pd, echo=FALSE, results='asis'}
pd_paths = pd_path(root = cfg$root_path, version = cfg$version)

embed_pd(path_obj = pd_paths)
```
