---
title: "OBIS Ccar Maxent/net"
output: html_notebook
---


``` {r}
suppressPackageStartupMessages({
  library(obisniche)
  library(dplyr)
  library(ENMeval)
  library(maxnet)
  library(cofbb)
})
```



``` {r}
spp <- list_obis()
bb <- cofbb::get_bb("nwa2", "sf")
global_coast <- rnaturalearth::ne_coastline(returnclass = "sf")
nwa_coast <- sf::st_crop(global_coast, bb)
mask <- stars::read_stars("inst/ext_data/world_9km.tif") |>
  sf::st_crop(bb)

# g = sf::st_geometry(nwa_coast)
# sf::st_polygonize(g[2])
# sf::st_polygonize(sf::st_geometry(nwa_coast))

x <- read_obis(spp[1], dwc = TRUE) |>
  distinct() |>
  sf::st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) |>
  sf::st_crop(bb)

occs <- filter(x, eventDate > as.Date("2003-01-01"))
occs.spring <- seasonality(x, season = "spring")
occs.summer <- seasonality(x, season = "summer")
occs.autumn <- seasonality(x, season = "autumn")
occs.winter <- seasonality(x, season = "winter")

```

```{r}

envs <- c(
  climatology = read_covar("sst_climatology.tif"),
  spring = read_covar("sst_spring.tif"),
  summer = read_covar("sst_summer.tif"),
  autumn = read_covar("sst_autumn.tif"),
  winter = read_covar("sst_winter.tif")
) |>
  set_names(c("climatology", "spring", "summer", "autumn", "winter"))



```


```{r}
# Now, we project our point data to an equal-area projection, which converts our 
# degrees to meters, which is ideal for buffering (the next step). 
# We use the typical Eckert IV projection.
eckertIV <- "+proj=eck4 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
occs.sf <- sf::st_transform(occs, crs = eckertIV)
occs.spring.sf <- sf::st_transform(occs.spring, crs = eckertIV)
occs.summer.sf <- sf::st_transform(occs.summer, crs = eckertIV)
occs.autumn.sf <- sf::st_transform(occs.autumn, crs = eckertIV)
occs.winter.sf <- sf::st_transform(occs.winter, crs = eckertIV)


# Buffer all occurrences by 200 km, union the polygons together 
# (for visualization), and convert back to a form that the raster package 
# can use. Finally, we reproject the buffers back to WGS84 (lat/lon).

occs.buf <- sf::st_buffer(occs.sf, dist = 200000) |>
  sf::st_union() |> 
  sf::st_sf(crs = eckertIV) |>
  sf::st_transform(crs = sf::st_crs(envs)) |>
  sf::write_sf(file.path("~/Desktop/GradSchoolCode/packages/obis_thermal_niche/inst/ext_data", 
                         "occurrence_buf_climatology.gpkg"))

occs.spring.buf <- sf::st_buffer(occs.spring.sf, dist = 200000) |>
  sf::st_union() |> 
  sf::st_sf(crs = eckertIV) |>
  sf::st_transform(crs = sf::st_crs(envs))

occs.summer.buf <- sf::st_buffer(occs.summer.sf, dist = 200000) |>
  sf::st_union() |> 
  sf::st_sf(crs = eckertIV) |>
  sf::st_transform(crs = sf::st_crs(envs))

occs.autumn.buf <- sf::st_buffer(occs.autumn.sf, dist = 200000) |>
  sf::st_union() |> 
  sf::st_sf(crs = eckertIV) |>
  sf::st_transform(crs = sf::st_crs(envs))

occs.winter.buf <- sf::st_buffer(occs.winter.sf, dist = 200000) |>
  sf::st_union() |> 
  sf::st_sf(crs = eckertIV) |>
  sf::st_transform(crs = sf::st_crs(envs))


plot(envs[1], main = names(envs)[1], reset = FALSE)
# To add sf objects to a plot, use add = TRUE
plot(occs, add = TRUE, col = 'orange')
plot(occs.buf, border = "blue", lwd = 3, add = TRUE)

plot(envs[2], main = names(envs)[2], reset = FALSE)
plot(occs.spring, add = TRUE, col = 'orange')
plot(occs.spring.buf, border = 'blue', lwd = 3, add = TRUE)

plot(envs[3], main = names(envs)[3], reset = FALSE)
plot(occs.summer, add = TRUE, col = 'orange')
plot(occs.summer.buf, border = "blue", lwd = 3, add = TRUE)

plot(envs[4], main = names(envs)[4], reset = FALSE)
plot(occs.autumn, add = TRUE, col = 'orange')
plot(occs.autumn.buf, border = "blue", lwd = 3, add = TRUE)

plot(envs[5], main = names(envs)[5], reset = FALSE)
plot(occs.winter, add = TRUE, col = 'orange')
plot(occs.winter.buf, border = "blue", lwd = 3, add = TRUE)

# only one occurrence point (probably throw away/not do maxnet with it)

```

```{r}

# Crop environmental rasters to match the study extent
envs.bg <- sf::st_crop(envs, occs.buf)
# Next, mask the rasters to the shape of the buffers
envs.bg <- envs.bg[occs.buf]
plot(envs.bg[1], main = names(envs)[1], reset = FALSE)
plot(occs, col = 'orange', add = TRUE)
plot(occs.buf, border = "blue", lwd = 3, add = TRUE)


envs.spring.bg = sf::st_crop(envs[2], occs.spring.buf)
envs.spring.bg = envs.spring.bg[occs.spring.buf]
plot(envs.spring.bg[1], main = names(envs)[2], reset = FALSE)
plot(occs.spring, col = "orange", add = TRUE)
plot(occs.spring.buf, border = "blue", lwd = 3, add = TRUE)

envs.summer.bg = sf::st_crop(envs[3], occs.summer.buf)
envs.summer.bg = envs.summer.bg[occs.summer.buf]
plot(envs.summer.bg[1], main = names(envs)[3], reset = FALSE)
plot(occs.summer, col = "orange", add = TRUE)
plot(occs.summer.buf, border = "blue", lwd = 3, add = TRUE)

envs.autumn.bg = sf::st_crop(envs[4], occs.autumn.buf)
envs.autumn.bg = envs.autumn.bg[occs.autumn.buf]
plot(envs.autumn.bg[1], main = names(envs)[4], reset = FALSE)
plot(occs.autumn, col = "orange", add = TRUE)
plot(occs.autumn.buf, border = "blue", lwd = 3, add = TRUE)

envs.winter.bg = sf::st_crop(envs[5], occs.winter.buf)
envs.winter.bg = envs.winter.bg[occs.winter.buf]
plot(envs.winter.bg[1], main = names(envs)[5], reset = FALSE)
plot(occs.winter, col = "orange", add = TRUE)
plot(occs.winter.buf, border = "blue", lwd = 3, add = TRUE)


```


```{r}

# Randomly sample 10,000 background points from one background extent raster 
# (only one per cell without replacement). Note: Since the raster has <10,000 pixels, 
# you'll get a warning and all pixels will be used for background. We will be sampling 
# from the biome variable because it is missing some grid cells, and we are trying to 
# avoid getting background points with NA. If one raster in the stack has NAs where the
# other rasters have data, ENMeval internally converts these cells to NA.
N <- 10000
bg <- sf::st_sample(occs.buf, N) |>
  sf::st_as_sf() |>
  sf::st_set_geometry("geometry") |>
  sf::write_sf(file.path("~/Desktop/GradSchoolCode/packages/obis_thermal_niche/inst/ext_data", 
                         paste0("buffered_bg_points_", N, ".gpkg")))

spring.bg = sf::st_sample(occs.spring.buf, N) |>
  sf::st_as_sf() |>
  sf::st_set_geometry("geometry")

summer.bg = sf::st_sample(occs.summer.buf, N) |>
  sf::st_as_sf() |>
  sf::st_set_geometry("geometry")

autumn.bg = sf::st_sample(occs.autumn.buf, N) |>
  sf::st_as_sf() |>
  sf::st_set_geometry("geometry")

# Notice how we have pretty good coverage (every cell).
plot(envs.bg[1], reset = FALSE)
plot(bg, add = TRUE, pch = ".", col = 'orange')

plot(envs.spring.bg[1], reset = FALSE)
plot(spring.bg, add = TRUE, pch = ".", col = "orange")

plot(envs.summer.bg[1], reset = FALSE)
plot(summer.bg, add = TRUE, pch = ".", col = "orange")

plot(envs.autumn.bg[1], reset = FALSE)
plot(autumn.bg, add = TRUE, pch = ".", col = "orange")

```

```{r}

occsr = as_dataframe(occs) |>
  dplyr::select(c("longitude", "latitude"))

occsr.spring = as_dataframe(occs.spring) |>
  dplyr::select(c("longitude", "latitude"))


bgr = as_dataframe(bg)

bgr.spring = as_dataframe(spring.bg)


envsr = as(envs, "Raster")

envsr.spring = as(envs[2], "Raster")

occsr.spring = dplyr::mutate(occsr.spring, sst = raster::extract(envsr.spring, occsr.spring))
bgr.spring = dplyr::mutate(bgr.spring, sst = raster::extract(envsr.spring, bgr.spring))
saveRDS(bgr.spring, file = "bgr.spring.RDS")
saveRDS(occsr.spring, file = "occsr.spring.RDS")

e.mx.l <- ENMevaluate(occs = occsr, envs = envsr, bg = bgr, 
                      algorithm = 'maxnet', partitions = 'block', 
                      tune.args = list(fc = "L", rm = 1:2))

e.mx.l.spring <- ENMevaluate(occs = occsr.spring, 
                             # envs = envsr.spring,
                             bg = bgr.spring,
                             algorithm = 'maxnet', partitions = 'block',
                             tune.args = list(fc = "L", rm = 1:2))

raster::plot(e.mx.l@predictions, col=colorRampPalette(c("white", "blue"))(255))
```
